apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.analysis.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloud-native-bench.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloud-native-bench.analysis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloud-native-bench.analysis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.analysis.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.analysis.image.repository }}:{{ .Values.analysis.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.analysis.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:admin@{{ .Release.Name }}-postgresql.benchmark-operator.svc.cluster.local:5432/benchmarks"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

