apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloud-native-bench.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "cloud-native-bench.labels" . | nindent 4 }}
