apiVersion: v1
kind: ServiceAccount
metadata:
  name: { { include "cloud-native-bench.serviceAccountName" . } }
  namespace: { { .Values.namespace } }
  labels: { { - include "cloud-native-bench.labels" . | nindent 4 } }
