apiVersion: v1
kind: Service
metadata:
  name: { { .Values.web.service.name } }
  namespace: { { .Values.namespace } }
  labels: { { - include "cloud-native-bench.labels" . | nindent 4 } }
spec:
  type: { { .Values.web.service.type } }
  ports:
    - port: 80
      targetPort: { { .Values.web.service.port } }
      protocol: TCP
      name: http
  selector:
    { { - include "cloud-native-bench.web.selectorLabels" . | nindent 4 } }
